changes we add:
On branch thread
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   Makefile
	modified:   notxv6/barrier.c
	modified:   notxv6/ph.c
	modified:   user/sh.c
	modified:   user/uthread.c
	modified:   user/uthread_switch.S

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	answers-thread.txt
	solutions/
	time.txt

no changes added to commit (use "git add" and/or "git commit -a")

